model_name: "policy_27.pt"
framework: "isaacgym"
rows: 2
cols: 3
use_history: False
dt: 0.005
decimation: 2
num_observations: 27
observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
clip_obs: 100.0
clip_actions_lower: [-100, -100, -100,
                     -100, -100, -100]
clip_actions_upper: [100, 100, 100,
                     100, 100, 100]

#  maybe could use in stand
#  fixed_kp: [80, 80, 80,
#             80, 80, 80]
#  fixed_kd: [3, 3, 3,
#             3, 3, 3]

num_of_dofs: 6
action_scale: 0.5
lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05

commands_scale: [2.0, 0.25, 5.0]
torque_limits: [26, 26, 26,
                26, 26, 26]
#default_dof_pos: [ 0, 0, 0.0,
#                   0, 0, 0.0]
default_dof_pos: [ 0.65, -1.25, 0.0,
                   0.65, -1.25, 0.0]
